name: app
description: Aplicativo para organização de rotina e finanças.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  flutter_modular: ^5.0.3
  sqflite: ^2.2.0+2
  dartz: ^0.10.1
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  intl: ^0.17.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  sqflite_common_ffi: ^2.1.1+1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
